"""Build data/descriptions_utzap_claude.json with leakage-controlled descriptions for UT-Zappos.

Generated by Claude Opus 4.7 directly in the conversation (no API call).

UT-Zap primitives: 16 attrs (materials) + 12 objs (shoe types).
Leakage rules:
- ATTR (material) descriptions: must not contain other attrs' identifying tokens, must not
  contain shoe-type tokens. Tokens shared with the description's own attr are allowed.
- OBJ (shoe-type) descriptions: must not contain material tokens, must not contain other
  shoe-type tokens. Tokens shared with the description's own obj are allowed.

K=3 uniform.
"""
import json
import re
from pathlib import Path


ATTRS_LIST = [
    "Canvas", "Cotton", "Faux.Fur", "Faux.Leather", "Full.grain.leather", "Hair.Calf",
    "Leather", "Nubuck", "Nylon", "Patent.Leather", "Rubber", "Satin", "Sheepskin",
    "Suede", "Synthetic", "Wool",
]

OBJS_LIST = [
    "Boots.Ankle", "Boots.Knee.High", "Boots.Mid-Calf", "Sandals", "Shoes.Boat.Shoes",
    "Shoes.Clogs.and.Mules", "Shoes.Flats", "Shoes.Heels", "Shoes.Loafers",
    "Shoes.Oxfords", "Shoes.Sneakers.and.Athletic.Shoes", "Slippers",
]


# tokens that appear inside primitive names but are too generic to count as leakage
# ("and" comes from "Shoes.Clogs.and.Mules" / "Shoes.Sneakers.and.Athletic.Shoes",
#  "high" is also generic-positional). We keep the rest strict.
GENERIC_NAME_TOKENS = {"and", "high"}


def tokens_of(name: str) -> set:
    return set(re.findall(r"[a-z]+", name.lower())) - GENERIC_NAME_TOKENS


# ============ ATTRS (materials) ============
# Each entry: 3 descriptions focused on physical surface properties
# (texture, sheen, weave, fibers, finish, gloss). Avoid naming other materials
# or shoe types.

ATTRS = {}

ATTRS["Canvas"] = [
    "a heavy plain-weave fabric with visible grid texture and matte finish",
    "a thick woven textile with coarse weft-warp pattern visible across the surface",
    "a sturdy planar material with rough natural-fiber feel and low light reflection",
]

ATTRS["Cotton"] = [
    "a soft fibrous textile with fine fluffy surface and moderate matte appearance",
    "a breathable woven fabric with smooth flat finish and light absorbing tone",
    "a natural-fiber material with even uniform texture and dull non-reflective look",
]

ATTRS["Faux.Fur"] = [
    "a long-pile plush surface with raised upright fibers and soft volumetric texture",
    "a fluffy strand-rich coating with matted thread-like elements and deep tactile depth",
    "a man-made plush layer with elongated pile creating shadowed crevices between strands",
]

ATTRS["Faux.Leather"] = [
    "a coated polymer-finish surface with smooth seamless appearance and moderate-gloss sheen",
    "a faux skin-like material with even uniform texture and no natural pore pattern",
    "an artificial finish mimicking an organic surface with regular embossed pattern and slight sheen",
]

ATTRS["Full.grain.leather"] = [
    "a thick organic surface showing visible pore pattern with full natural grain detail",
    "a hide material with pronounced surface relief, scars, and irregular tonal variation",
    "a dense skin-derived surface with raw grain pattern and semi-matte tactile depth",
]

ATTRS["Hair.Calf"] = [
    "a short-pile pelt surface with directional bristles lying flat in one orientation",
    "a smooth bristle-textured layer with uniform short follicles aligned across the surface",
    "a fine-piled hide material with subtle directional sheen from aligned hair fibers",
]

ATTRS["Leather"] = [
    "a tanned-hide surface with smooth even pore pattern and rich semi-matte appearance",
    "an organic-skin material with subtle natural texture and warm tonal depth",
    "a pliable hide-derived material with uniform finish, slight sheen, and dense feel",
]

ATTRS["Nubuck"] = [
    "a velvet-like brushed-hide surface with very fine fibrous nap, soft to touch",
    "a sanded skin material with short fuzzy fibers and a velvety matte appearance",
    "a buffed-hide finish with delicate microscopic nap, no gloss, soft tactile texture",
]

ATTRS["Nylon"] = [
    "a manufactured woven thread textile with smooth tightly-knit surface and slight sheen",
    "a polymer-fiber fabric with fine even weave and durable smooth appearance",
    "a man-made textile with regular thread pattern showing glossy highlights under light",
]

ATTRS["Patent.Leather"] = [
    "a high-gloss mirror-finish surface with strong reflective coating",
    "a deeply lacquered skin-material with intense glassy shine and smooth uniform look",
    "an enameled-hide surface with extreme sheen, reflective like a polished mirror",
]

ATTRS["Rubber"] = [
    "an elastomeric solid surface with matte uniform texture and slightly tacky look",
    "a flexible polymer material with even bouncy appearance and low gloss finish",
    "a vulcanized polymer surface with consistent texture and a low-luster finish",
]

ATTRS["Satin"] = [
    "a smooth lustrous textile with high-sheen flat surface and fluid drape",
    "a glossy woven fabric with directional luster and soft reflective finish",
    "a silky-finish textile with uniform sheen and smooth flowing surface",
]

ATTRS["Sheepskin"] = [
    "a thick fiber-bearing hide with curly dense fibers on one side and smooth surface on the other",
    "a fluffy fiber-bearing pelt with deep curly nap and plush volume",
    "a fiber-bearing hide material with tight crinkled fiber pattern and dense pile",
]

ATTRS["Suede"] = [
    "a brushed underside hide with soft fuzzy short-pile texture",
    "a velvet-like nap surface from inside a hide, matte and tactile",
    "a soft fibrous-finish material with uniform fine fuzzy pile and no shine",
]

ATTRS["Synthetic"] = [
    "a polymer-fiber surface with uniform machine-made pattern and no natural variation",
    "a man-made composite material with even regular surface and consistent finish",
    "an artificial-fiber material with predictable geometric pattern and engineered surface",
]

ATTRS["Wool"] = [
    "a woven fiber textile with fuzzy soft surface and slight tactile depth",
    "a thick natural-fiber fabric with woolen nap and warm matte appearance",
    "a knit or felted textile with crimped fibers visible and dense soft texture",
]


# ============ OBJS (shoe types) ============
# Each entry: 3 descriptions focused on shoe form (silhouette, height, opening,
# sole, fastening, posture). Avoid naming materials.

OBJS = {}

OBJS["Boots.Ankle"] = [
    "a footwear silhouette covering up to the lower leg joint with rising shaft above the foot",
    "a closed-toe form with shaft height reaching just above the foot opening",
    "a covering form with low shaft height and snug fit around the lower leg base",
]

OBJS["Boots.Knee.High"] = [
    "a tall footwear silhouette with shaft extending up to the lower thigh joint",
    "an elongated covering form rising from foot upward to half the lower leg with vertical shaft",
    "a high-shaft form covering most of the lower leg with continuous upward profile",
]

OBJS["Boots.Mid-Calf"] = [
    "a footwear silhouette with shaft height reaching halfway up the lower leg",
    "a mid-shaft covering form ending at the widest part of the lower leg",
    "an upper-form rising past the foot opening to roughly the midpoint of the lower leg",
]

OBJS["Sandals"] = [
    "an open footwear form with exposed top of foot and minimal upper coverage",
    "a strapped form with thin bands across the top and an open profile",
    "a flat-base footwear form with airy openings and exposed toes",
]

OBJS["Shoes.Boat.Shoes"] = [
    "a low-cut casual form with flat sole and lacing across the top of foot",
    "a slip-on or lightly-laced form with low silhouette and rounded toe",
    "a moc-style form with stitched seam around the upper edge and flat profile",
]

OBJS["Shoes.Clogs.and.Mules"] = [
    "a backless slip-on form with closed front and open heel section",
    "a heel-free form with enclosed toe area and exposed back of foot",
    "an easy-on form with no rear strap and a covered front portion",
]

OBJS["Shoes.Flats"] = [
    "a low-profile footwear form with thin flat sole and minimal vertical lift",
    "a thin-soled form sitting close to the ground with no raised heel section",
    "a planar footwear form with even sole height from front to back",
]

OBJS["Shoes.Heels"] = [
    "a footwear form with elevated rear section raising the foot at an angle",
    "a tilted-foot silhouette with tall back support and pointed or rounded front",
    "an angled-base form with significant rear elevation creating forward-tilted posture",
]

OBJS["Shoes.Loafers"] = [
    "a slip-on form with no laces and a low rounded silhouette",
    "a moccasin-derived form with stitched apron front and easy entry",
    "a closed front form with smooth uppers and absence of fastening hardware",
]

OBJS["Shoes.Oxfords"] = [
    "a low-cut laced form with closed lacing system and structured upper",
    "a formal silhouette with tongue beneath crossed laces and clean toe profile",
    "a tightly-laced form with eyelets sewn under the vamp and a polished outline",
]

OBJS["Shoes.Sneakers.and.Athletic.Shoes"] = [
    "a thick-soled cushioned form with padded collar and flexible upper",
    "a lace-up footwear form with bouncy sole and breathable mesh upper portions",
    "a sport-oriented silhouette with grippy outsole and supportive collar area",
]

OBJS["Slippers"] = [
    "a soft indoor footwear form with plush lining and easy slip-on profile",
    "a low-structure foot covering with minimal sole and very light feel",
    "a relaxed-fit form with cushioned interior and unstructured exterior shape",
]


def main():
    out = {
        "attrs": {a: {"sub": ATTRS[a], "K": len(ATTRS[a]), "d_sem": {}} for a in ATTRS_LIST},
        "objs": {o: {"sub": OBJS[o], "K": len(OBJS[o]), "d_sem": {}} for o in OBJS_LIST},
    }

    print("=== validation ===")
    flags = []

    # Token sets per primitive
    attr_toks = {a: tokens_of(a) for a in ATTRS_LIST}
    obj_toks = {o: tokens_of(o) for o in OBJS_LIST}
    all_attr_toks = set().union(*attr_toks.values())
    all_obj_toks = set().union(*obj_toks.values())

    for a, subs in ATTRS.items():
        own = attr_toks[a]
        # tokens forbidden in this attr's descriptions
        forbid_other_attrs = (all_attr_toks - own)
        forbid_objs = (all_obj_toks - own)  # shoe-type words leak attr-obj pair
        for i, s in enumerate(subs):
            words = set(re.findall(r"[a-z]+", s.lower()))
            bad_a = words & forbid_other_attrs
            bad_o = words & forbid_objs
            if bad_a or bad_o:
                flags.append((a, i, sorted(bad_a), sorted(bad_o), s))

    for o, subs in OBJS.items():
        own = obj_toks[o]
        forbid_attrs = (all_attr_toks - own)  # material words
        forbid_other_objs = (all_obj_toks - own)
        for i, s in enumerate(subs):
            words = set(re.findall(r"[a-z]+", s.lower()))
            bad_a = words & forbid_attrs
            bad_o = words & forbid_other_objs
            if bad_a or bad_o:
                flags.append((o, i, sorted(bad_a), sorted(bad_o), s))

    if flags:
        print(f"FLAGGED {len(flags)} description(s) with leakage:")
        for prim, i, bad_a, bad_o, s in flags:
            marks = []
            if bad_a: marks.append(f"attrs={bad_a}")
            if bad_o: marks.append(f"objs={bad_o}")
            print(f"  [{prim}#{i}] {' '.join(marks)} :: {s}")
    else:
        print("OK: no leakage detected")

    print(f"\n=== counts ===")
    print(f"attrs: {len(ATTRS)} of {len(ATTRS_LIST)} expected, sum_K={sum(len(v) for v in ATTRS.values())}")
    print(f"objs:  {len(OBJS)} of {len(OBJS_LIST)} expected, sum_K={sum(len(v) for v in OBJS.values())}")
    missing_a = [a for a in ATTRS_LIST if a not in ATTRS]
    missing_o = [o for o in OBJS_LIST if o not in OBJS]
    if missing_a: print(f"MISSING attrs: {missing_a}")
    if missing_o: print(f"MISSING objs:  {missing_o}")

    out_path = Path(__file__).resolve().parent.parent / "data" / "descriptions_utzap_claude.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"\nwrote {out_path}")

    if flags:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
